-- MySQL Script generated by MySQL Workbench
-- Wed Jul 14 23:02:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teachagogo_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teachagogo_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teachagogo_dev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `teachagogo_dev` ;

-- -----------------------------------------------------
-- Table `donations_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donations_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_default` TINYINT(1) NOT NULL DEFAULT 0,
  `tier_1` JSON NOT NULL,
  `tier_2_onset` INT NOT NULL DEFAULT 3,
  `tier_2` JSON NULL,
  `tier_3_onset` INT NOT NULL DEFAULT 5,
  `tier_3` JSON NULL,
  `placement` ENUM('prompt', 'sidebar') NOT NULL DEFAULT 'prompt',
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(100) NOT NULL,
  `last_sign_in_date` DATETIME NULL,
  `is_zombie` INT NULL,
  `donation_date` DATETIME NULL,
  `donated_options_id` INT NULL,
  `alias_first_name` VARCHAR(45) NULL,
  `alias_last_name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `email_payout` VARCHAR(45) NULL,
  `avatar_locator` VARCHAR(255) NULL,
  `communication_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `portfolio_module` ENUM('about', 'tip', 'message', 'share') NOT NULL DEFAULT 'about',
  `about_me` VARCHAR(255) NULL,
  `role` ENUM('teacher', 'admin') NOT NULL DEFAULT 'teacher',
  `marketing_email_enabled` INT(1) NULL DEFAULT 1,
  `is_deactivated` TINYINT(1) NOT NULL DEFAULT 0,
  `is_dormant` TINYINT(1) NOT NULL DEFAULT 0,
  `dormancy_reason` ENUM('no_sign_in', 'excess_funds') NULL,
  `dormancy_date` DATETIME NULL,
  `timezone_offset` INT(1) NOT NULL DEFAULT 300,
  `tos_accepted_at` DATETIME NULL,
  `is_usa_resident` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `email_payout_UNIQUE` (`email_payout` ASC),
  INDEX `fk_users_donations_options1_idx` (`donated_options_id` ASC),
  CONSTRAINT `fk_users_donations_options1`
    FOREIGN KEY (`donated_options_id`)
    REFERENCES `donations_options` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `login` TINYINT(1) NOT NULL DEFAULT 1,
  `download` TINYINT(1) NOT NULL DEFAULT 1,
  `upload` TINYINT(1) NOT NULL DEFAULT 1,
  `editing` TINYINT(1) NOT NULL DEFAULT 1,
  `controls` TINYINT(1) NOT NULL DEFAULT 1,
  `income` TINYINT(1) NOT NULL DEFAULT 1,
  `payouts` TINYINT(1) NOT NULL DEFAULT 1,
  `payments` TINYINT(1) NOT NULL DEFAULT 1,
  `advertise` TINYINT(1) NOT NULL DEFAULT 1,
  `messages` TINYINT(1) NOT NULL DEFAULT 1,
  `follow` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_permissions_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_permissions_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `users_id_related` INT NULL,
  `type` ENUM("tip_received", "tip_given", "donation", "revenue_share", "adjustment", "payout", "top_up") NOT NULL,
  `amount` INT NOT NULL,
  `status` ENUM("awaiting_approval", "rejected", "completed") NOT NULL,
  `memo` VARCHAR(45) NULL,
  `fingerprint` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_transactions_users1_idx` (`users_id` ASC),
  INDEX `fk_users_transactions_users2_idx` (`users_id_related` ASC),
  CONSTRAINT `fk_users_transactions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_transactions_users2`
    FOREIGN KEY (`users_id_related`)
    REFERENCES `users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `subtitle` VARCHAR(45) NOT NULL,
  `subject_area` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `keywords` VARCHAR(255) NULL,
  `skills` VARCHAR(150) NULL,
  `reading_levels` VARCHAR(150) NULL,
  `standards` VARCHAR(150) NULL,
  `grade` VARCHAR(45) NULL,
  `approval_status` ENUM("awaiting_approval", "rejected", "approved") NULL,
  `rejected_at` DATETIME NULL,
  `moderator_comment` VARCHAR(255) NULL,
  `curator_score` INT NOT NULL DEFAULT 50,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_resources_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_resources_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_users_favorites_users1_idx` (`users_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_users_favorites_resources1_idx` (`resources_id` ASC),
  CONSTRAINT `fk_users_favorites_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_favorites_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `resources` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resources_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resources_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resources_id` INT NOT NULL,
  `locator` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_resources_files_resources1_idx` (`resources_id` ASC),
  CONSTRAINT `fk_resources_files_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resources_previews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resources_previews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resources_id` INT NOT NULL,
  `locator` VARCHAR(45) NULL,
  `order_index` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_resources_previews_resources1_idx` (`resources_id` ASC),
  CONSTRAINT `fk_resources_previews_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `resources` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referrals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referrals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `affiliate_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `landing_uri` VARCHAR(255) NOT NULL,
  `commission_percentage_affiliate` INT NOT NULL DEFAULT 25,
  `expiration_date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_referrals_users2_idx` (`affiliate_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_referrals_users2`
    FOREIGN KEY (`affiliate_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resources_downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resources_downloads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `referrals_id` INT NULL,
  `ip_address` VARCHAR(45) NULL,
  `download_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_resources_downloads_resources1_idx` (`resources_id` ASC),
  INDEX `fk_resources_downloads_users1_idx` (`users_id` ASC),
  INDEX `fk_resources_downloads_referrals1_idx` (`referrals_id` ASC),
  CONSTRAINT `fk_resources_downloads_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `resources` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resources_downloads_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resources_downloads_referrals1`
    FOREIGN KEY (`referrals_id`)
    REFERENCES `referrals` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ad_type` ENUM("1", "2", "3", "4") NOT NULL,
  `placement` ENUM("site", "portfolio") NOT NULL,
  `title` VARCHAR(45) NULL,
  `subtitle` VARCHAR(45) NULL,
  `subject` VARCHAR(45) NULL,
  `click_url` VARCHAR(45) NULL,
  `image_url` VARCHAR(45) NULL,
  `statement` VARCHAR(45) NULL,
  `spend_per_day` INT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `approval_status` ENUM("awaiting_approval", "rejected", "approved") NULL,
  `rejected_at` DATETIME NULL,
  `moderator_comment` VARCHAR(255) NULL,
  `running_status` ENUM("running", "stopped") NULL,
  `users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_advertisements_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_advertisements_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisements_target_grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisements_target_grades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `advertisements_id` INT NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_advertisements_target_grades_advertisements1_idx` (`advertisements_id` ASC),
  CONSTRAINT `fk_advertisements_target_grades_advertisements1`
    FOREIGN KEY (`advertisements_id`)
    REFERENCES `advertisements` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisements_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisements_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `record_type` ENUM('impression', 'click') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT NULL,
  `advertisements_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_advertisements_records_advertisements1_idx` (`advertisements_id` ASC),
  INDEX `fk_advertisements_records_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_advertisements_records_advertisements1`
    FOREIGN KEY (`advertisements_id`)
    REFERENCES `advertisements` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_advertisements_records_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donations_options_id` INT NOT NULL,
  `donation_options_tier` INT NOT NULL,
  `donation_amount` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_donations_donations_options1_idx` (`donations_options_id` ASC),
  INDEX `fk_donations_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_donations_donations_options1`
    FOREIGN KEY (`donations_options_id`)
    REFERENCES `donations_options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donations_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_balances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_balances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `affiliate_revenue` INT NOT NULL DEFAULT 0,
  `expenses` INT NOT NULL DEFAULT 0,
  `skip_manual_balances` TINYINT(1) NOT NULL DEFAULT 0,
  `is_finalized` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email_templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `text_content` VARCHAR(2000) NULL,
  `html_content` VARCHAR(2000) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email_scheduled_sends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email_scheduled_sends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `send_at_date` DATETIME NOT NULL,
  `sent_status` ENUM("unsent", "sent") NOT NULL DEFAULT 'unsent',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email_templates_id` INT NOT NULL,
  `email_values` JSON NULL,
  PRIMARY KEY (`id`, `email_templates_id`),
  INDEX `fk_email_scheduled_sends_users1_idx` (`users_id` ASC),
  INDEX `fk_email_scheduled_sends_email_templates1_idx` (`email_templates_id` ASC),
  CONSTRAINT `fk_email_scheduled_sends_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_scheduled_sends_email_templates1`
    FOREIGN KEY (`email_templates_id`)
    REFERENCES `email_templates` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captcha_solutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captcha_solutions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clue` VARCHAR(255) NOT NULL,
  `solution` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captcha_challenges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captcha_challenges` (
  `id` VARCHAR(16) NOT NULL,
  `captcha_solutions_id` INT NOT NULL,
  `solution_order` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_captcha_challenges_captcha_solutions1_idx` (`captcha_solutions_id` ASC),
  CONSTRAINT `fk_captcha_challenges_captcha_solutions1`
    FOREIGN KEY (`captcha_solutions_id`)
    REFERENCES `captcha_solutions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `token_heartbeats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `token_heartbeats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token_hash` VARCHAR(100) NOT NULL,
  `last_heartbeat` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_token_heartbeats_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_token_heartbeats_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `value` JSON NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_text` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` TEXT(2000) NOT NULL,
  `description` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `locator_backup` VARCHAR(255) NOT NULL,
  `locator_current` VARCHAR(255) NOT NULL,
  `description` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `help_center_entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help_center_entries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_index` INT NOT NULL,
  `short_title` VARCHAR(45) NOT NULL,
  `long_title` VARCHAR(255) NOT NULL,
  `body` VARCHAR(2000) NOT NULL DEFAULT '',
  `image_locator` VARCHAR(255) NULL,
  `accent_color` VARCHAR(20) NULL,
  `keywords` VARCHAR(1000) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tos_updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purged_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purged_accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `purge_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_2fa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_2fa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `email_mobile` VARCHAR(45) NULL,
  `password` VARCHAR(100) NOT NULL,
  `password_unlock` VARCHAR(100) NOT NULL,
  `recent_tries` INT NOT NULL DEFAULT 0,
  `last_verification` DATETIME NULL,
  `state` ENUM('unlocked', 'locked') NOT NULL DEFAULT 'unlocked',
  `users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_2fa_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_2fa_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email_proxy_threads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email_proxy_threads` (
  `id` VARCHAR(20) NOT NULL,
  `users_id_a` INT NOT NULL,
  `users_id_b` INT NOT NULL,
  `last_activity` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_support_thread` TINYINT(1) NOT NULL DEFAULT 0,
  `is_resolved` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_email_proxy_threads_users1_idx` (`users_id_a` ASC),
  INDEX `fk_email_proxy_threads_users2_idx` (`users_id_b` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_email_proxy_threads_users1`
    FOREIGN KEY (`users_id_a`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_proxy_threads_users2`
    FOREIGN KEY (`users_id_b`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduled_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduled_jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `minute` VARCHAR(10) NOT NULL DEFAULT '*',
  `hour` VARCHAR(10) NOT NULL DEFAULT '*',
  `day_of_month` VARCHAR(10) NOT NULL DEFAULT '*',
  `month` VARCHAR(10) NOT NULL DEFAULT '*',
  `day_of_week` VARCHAR(10) NOT NULL DEFAULT '?',
  `enabled` INT(1) NOT NULL DEFAULT 0,
  `last_run` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduled_jobs_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduled_jobs_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `scheduled_jobs_id` INT NOT NULL,
  `success` INT(1) NOT NULL DEFAULT 0,
  `info` VARCHAR(2000) NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_scheduled_jobs_log_scheduled_jobs1_idx` (`scheduled_jobs_id` ASC),
  CONSTRAINT `fk_scheduled_jobs_log_scheduled_jobs1`
    FOREIGN KEY (`scheduled_jobs_id`)
    REFERENCES `scheduled_jobs` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_following` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `users_id_following` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_following_users1_idx` (`users_id` ASC),
  INDEX `fk_users_following_users2_idx` (`users_id_following` ASC),
  CONSTRAINT `fk_users_following_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_following_users2`
    FOREIGN KEY (`users_id_following`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email_opt_out_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email_opt_out_links` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_email_opt_out_links_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_email_opt_out_links_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_login_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_login_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_following_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_following_users10`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_ips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_ips` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_users_ips_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_ips_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_stats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `new_users` INT NOT NULL,
  `total_users` INT NOT NULL,
  `unique_logins` INT NOT NULL,
  `active_resources` INT NOT NULL,
  `new_resources` INT NOT NULL,
  `total_resources` INT NOT NULL,
  `resource_downloads` INT NOT NULL,
  `income_per_download` INT NOT NULL,
  `ad_impressions` INT NOT NULL,
  `ad_spend` INT NOT NULL,
  `total_donations` INT NOT NULL,
  `total_income` INT NOT NULL,
  `misc_income` INT NOT NULL,
  `dormancy_income` INT NOT NULL,
  `total_tips` INT NOT NULL,
  `total_revenue` INT NOT NULL,
  `total_unpaid_earnings` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support_thread_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support_thread_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_proxy_threads_id` VARCHAR(20) NOT NULL,
  `users_id_from` INT NOT NULL,
  `message` VARCHAR(5000) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_support_thread_messages_email_proxy_threads1_idx` (`email_proxy_threads_id` ASC),
  INDEX `fk_support_thread_messages_users1_idx` (`users_id_from` ASC),
  CONSTRAINT `fk_support_thread_messages_email_proxy_threads1`
    FOREIGN KEY (`email_proxy_threads_id`)
    REFERENCES `email_proxy_threads` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_support_thread_messages_users1`
    FOREIGN KEY (`users_id_from`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_donations_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_donations_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donations_options_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `num_donation_option_prompts` INT NULL DEFAULT 0,
  `num_donation_prompts_total` INT NULL DEFAULT 0,
  `last_donation_prompt` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_donations_donations_options1_idx` (`donations_options_id` ASC),
  INDEX `fk_donations_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_donations_donations_options10`
    FOREIGN KEY (`donations_options_id`)
    REFERENCES `donations_options` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donations_users10`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
